CLASS LHC_ZZCIR_CIT_STG_22EC086086 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZzcirCitStg22ec086086
        RESULT result.
ENDCLASS.

CLASS LHC_ZZCIR_CIT_STG_22EC086086 IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
